server:
  port: 9999

spring:
  thymeleaf:
    cache: false
  profiles:
    include:
      - dev
      - dev-oauth
#      - local
#      - local-oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher